name: First Workflow

on:
  push:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Print Message
        run: echo "Hello GitHub Actions"

      - name: Repository Name
        run: echo ${{ github.repository }}